name: Environment
on:
  workflow_dispatch:
    inputs:
      TARGET_ENVIRONMENT:
        type: environment
        default: dev
jobs:
  echo_env: 
    runs-on: ubuntu-latest
    environment: ${{inputs.TARGET_ENVIRONMENT}}
    steps:
      - run: echo "production Env Var is ${{vars.PROD_VAR}}"
      - run: echo "Dev Env Var is ${{vars.DEV_VAR}}"
      - run: echo "Dev Secret var is ${{secrets.DEV_SECRET}}"
      - run: echo "production Secret var is ${{secrets.PROD_SECRET}}"
    
