name: Expression
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo-expression:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Print startup info'
        if: ${{inputs.debug}}
        run: |
          echo "Triggered by ${{github.event_name}}"
          echo "Branch is ${{github.ref}}"
      - name: '[debug] print when triggerd from master'
        if: ${{inputs.debug && github.ref == 'refs/heads/master'}}
        run: echo "triggered from master"
    
