name: Github Contexts
on:
  push:
jobs:
  echo_github_contexts:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Action is ${{github.action}}"
        echo "Action path is ${{github.action_path}}"
    
    
  
