name: Input context
run-name: Inputs | DEBUG - {{$inputs.debug}}
on:
  workflow_dispatch:
    inputs:
      debug:
        default: false
        type: boolean

jobs:
  echo_data:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy build to target
        run: echo "Debug is {{$inputs.debug}}"
