name: Input context
run-name: Inputs | {{$inputs.debug}}
on:
  workflow_dispatch:
    inputs:
      debug:
        default: False
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy build to target
        run: echo "Debug is {{$inputs.debug}}"
