name: Input context
run-name: Inputs | DEBUG - ${{inputs.debug}}
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

jobs:
  echo_data:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Debug is ${{inputs.debug}}"
