name: matrix context
on:
  push
jobs:
  matrix_job:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version: [v22,v21]
    steps:
      - uses: actions/setup-node@v4.2.0
        with: 
          node-version: ${{matrix.node-version}}
      - run: echo "Running on ${{matrix.os}} and ${{matrix.node-version}}"
      
