name: Vars and secret contexts
on:
  - push
  - workflow_dispatch
jobs:
  echo_vars:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Variable value is ${{vars.VARIABLE}}"
  echo_secrect:
    runs-on: ubuntu-latest
    steps:
      - run: echo "secret is ${{secrets.PASSWORD}}"
      
      
