name: Log GitHub Context and Set User Variable

on:  
  push:
  pull_request:

jobs:
  log-user:
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub Event and Actor
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Triggered by: ${{ github.actor }}"

      - name: Set USER Variable
        run: echo "USER=${{ github.actor }}" >> $GITHUB_ENV

      - name: Print USER Variable
        run: echo "Workflow triggered by:$USER"
